Hazard type CRUD
mestafrica/ghana-hazard-reporter pull request #17
Opened 2024-07-30 12:04 UTC by DanSid

2024-07-31 11:44 UTC, sosualfred requested changes

2024-07-31 11:44 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +            });
Just 201 with a msg hazard created successfully is okay.

2024-07-31 11:45 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +            });
Can you use async await .then is not readable.

2024-08-01 08:19 UTC, sosualfred requested changes

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +        // });
Remove commented out code

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +        });
remove hazardType from the response.

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +        // });
Remove commented out code

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +            });
remove message

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +            });
update message to `Hazard updated successfully`, remove `hazardType`

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +        // });
Remove commented out code

2024-08-01 08:19 UTC, sosualfred commented on backend/src/controllers/hazardtypes.ts
> +        // });
Remove commented out code

2024-08-01 13:18 UTC, DanSid commented
Please @sosualfred I have made the validation and updates to the CRUD endpoints

2024-08-01 13:45 UTC, sosualfred commented
There are still some changes you've not made. But, I'll just go ahead and merge it.

2024-08-01 13:45 UTC, merged

2024-08-01 14:10 UTC, DanSid commented
Ok