Created Admin login UI
mestafrica/ghana-hazard-reporter pull request #61
Opened 2024-11-01 02:29 UTC by JoelCann

Created Admin login UI, did logic work and did API integration for that.

2024-11-01 07:58 UTC, sosualfred commented on frontend/src/pages/AdminLogin.tsx
> +        console.error("Email and password are required.");
Remove console logs from the code.

2024-11-01 08:00 UTC, sosualfred requested changes

2024-11-01 08:00 UTC, sosualfred commented on frontend/src/pages/AdminLogin.tsx
Remove console logs from the code.

2024-11-01 08:00 UTC, sosualfred commented on frontend/src/pages/login.tsx
Remove console logs from the code.

2024-11-01 08:00 UTC, sosualfred commented on frontend/.env.example
Don't delete the .env.example file

2024-11-01 13:36 UTC, JoelCann commented on frontend/.env.example
Yes please... I have returned it.

2024-11-05 08:00 UTC, sosualfred commented
It seems your changes are in the frontend folder instead of the admin folder.

2024-11-06 05:38 UTC, JoelCann commented
Yes please... I have resolved that.

2024-11-07 08:01 UTC, merged